/**
 * KY MON DON GIAP - BI KIP TOAN THU
 * Tra cứu toàn diện: Thập Can Khắc Ứng, Bát Môn Cung Khắc Ứng, Cửu Tinh Vượng Tướng, Bát Thần, 9 Độn, Tam Trá, Ngũ Giả, Kích Hình & Nhập Mộ
 */

export interface StemComboDetail {
  name: string; // Tên Cách Cục (vd: Thanh Long Phản Thủ)
  nature: 'Đại Cát' | 'Cát' | 'Bình Hòa' | 'Hung' | 'Đại Hung';
  poem?: string; // Khẩu quyết cổ thư
  meaning: string; // Diễn giải ý nghĩa
  career: string; // Quan vận & Sự nghiệp
  wealth: string; // Mưu tài cầu lợi
  travel: string; // Xuất hành & Cầu mưu
  health: string; // Bệnh tật & Kiện tụng
}

export interface DoorPalaceDetail {
  relation: string; // Môn Sinh Cung / Cung Sinh Môn / Tỷ Hòa / Môn Bách / Môn Chế / Phục Ngâm / Phản Ngâm
  status: 'Đại Cát' | 'Cát' | 'Bình' | 'Hung' | 'Đại Hung';
  description: string;
  staticSign: string; // Tĩnh Ứng (ở nhà, nội vụ, giao tế)
  dynamicSign: string; // Động Ứng (xuất hành, điềm triệu trên đường)
}

export interface StarDetail {
  element: string;
  originalPalace: number;
  seasonState: string; // Vượng / Tướng / Hưu / Tù / Phế
  meaning: string;
  advice: string;
}

export interface GodDetail {
  element: string;
  nature: string;
  significance: string;
  military: string; // Ứng dụng binh gia
  divination: string; // Dự trắc đời thường
}

// -------------------------------------------------------------------------------------------------
// 1. THẬP CAN KHẮC ỨNG (100 CẶP CAN THIÊN BÀN / ĐỊA BÀN THEO BÍ KÍP TOÀN THƯ)
// -------------------------------------------------------------------------------------------------
export const STEM_COMBINATIONS: Record<string, Record<string, StemComboDetail>> = {
  Mậu: {
    Mậu: {
      name: 'Phục Ngâm Mậu (Phục Ngâm Trọng Điệp)',
      nature: 'Hung',
      poem: 'Mậu gia Mậu hề bách sự bế, tĩnh thủ trì trọng mạc vọng động.',
      meaning: 'Hai Mậu trùng phùng, Thổ khí quá nặng làm bế tắc. Mọi việc đình trệ, tiền bạc đọng lại không lưu thông.',
      career: 'Quan vận trì trệ, không nên xin thăng chức hoặc đổi chỗ làm.',
      wealth: 'Đầu tư bị kẹt vốn, chôn vốn lâu dài, đòi nợ khó khăn.',
      travel: 'Xuất hành tắc đường, lỡ tàu xe, nên ở yên giữ nếp cũ.',
      health: 'Bệnh về tỳ vị, tiêu hóa, trướng bụng; kiện tụng kéo dài.',
    },
    Ất: {
      name: 'Thanh Long Hợp Linh (Thanh Long Đắc Thê)',
      nature: 'Cát',
      poem: 'Mậu gia Ất hề Long hợp linh, cầu quan tấn tước sự giai hanh.',
      meaning: 'Mậu Thổ gặp Ất Mộc âm dương hòa hợp, quý nhân nâng đỡ, âm dương tương tể.',
      career: 'Gặp cấp trên trợ lực, dễ có quý nhân nữ giới giúp đỡ thăng tiến.',
      wealth: 'Hợp tác kinh doanh có lời, sinh tài đắc lộc.',
      travel: 'Xuất hành phương này gặp bạn tốt tương trợ.',
      health: 'Bệnh mau thuyên giảm, gặp thầy thuốc giỏi.',
    },
    Bính: {
      name: 'Thanh Long Phản Thủ (Long Hồi Đầu)',
      nature: 'Đại Cát',
      poem: 'Mậu gia Bính hề Long phản thủ, bách sự giai thông vạn phúc tụ.',
      meaning: 'Đệ nhất Cát cách trong Kỳ Môn. Rồng quay đầu nhả ngọc, Bính Hỏa sinh Mậu Thổ quang minh lẫm liệt.',
      career: 'Thăng quan tiến chức, công danh rực rỡ, kiến công lập nghiệp lớn.',
      wealth: 'Tài lộc cuồn cuộn, mua bán đại lợi, đầu tư trúng lớn.',
      travel: 'Xuất hành trăm sự hanh thông, gặp may mắn tột cùng.',
      health: 'Bệnh nặng gặp thần y hóa lành, kiện tụng tất thắng.',
    },
    Đinh: {
      name: 'Thanh Long Diệu Minh (Long Đắc Quang)',
      nature: 'Cát',
      poem: 'Mậu gia Đinh hề quang diệu minh, kiến quý bái quan vạn lý trình.',
      meaning: 'Mậu Thổ gặp Đinh Hỏa tinh kỳ chiếu rọi, văn chương hiển đạt, danh tiếng lẫy lừng.',
      career: 'Thi cử đỗ đạt cao, thi tuyển xin việc đắc ý, nhận bằng khen.',
      wealth: 'Tiền bạc hanh thông qua trí tuệ, hợp đồng, văn hóa giáo dục.',
      travel: 'Xuất hành thuận buồm xuôi gió, được kính trọng.',
      health: 'Tâm thần an định, bệnh tim mạch mắt huyết áp ổn định.',
    },
    Kỷ: {
      name: 'Quý Nhân Nhập Ngục',
      nature: 'Hung',
      poem: 'Mậu gia Kỷ hề nhập ngục trung, công tư giai bất lợi sơ cùng.',
      meaning: 'Mậu là Thiên môn gặp Kỷ là Địa hộ, quý nhân bị giam hãm trong ngục tối.',
      career: 'Bị tiểu nhân gièm pha, cấp trên chèn ép, bế tắc công danh.',
      wealth: 'Tiền bạc thất thoát, hao tài vì việc mờ ám hoặc phạt vạ.',
      travel: 'Xuất hành dễ lạc đường, sa vào nơi rắc rối bất lợi.',
      health: 'Bệnh tỳ vị lâu ngày, kiện tụng dễ mang tiếng oan ức.',
    },
    Canh: {
      name: 'Trực Phù Phi Cung (Phi Cung Cách)',
      nature: 'Đại Hung',
      poem: 'Mậu gia Canh hề Trực Phù phi, cát biến vi hung sự sự nguy.',
      meaning: 'Canh Kim sát khí đánh bật Mậu Thổ. Chủ đổi dời, phá sản, biến cát thành hung.',
      career: 'Bị cách chức, mất quyền, công ty xáo trộn hoặc phá sản.',
      wealth: 'Mất mát tài sản lớn, trộm cắp lừa đảo, phá tài.',
      travel: 'Kỵ xuất hành, đề phòng tai nạn giao thông va chạm.',
      health: 'Bệnh cấp tính, gãy xương chấn thương; kiện tụng thất bại thảm hại.',
    },
    Tân: {
      name: 'Thanh Long Triết Túc (Rồng Gãy Chân)',
      nature: 'Hung',
      poem: 'Mậu gia Tân hề long triết túc, thủ phận an thường mạc tham dục.',
      meaning: 'Tân là âm Kim làm thương tổn gốc Mậu Thổ. Mưu sự gãy gánh giữa đường, chân tay tật bệnh.',
      career: 'Dự án nửa chừng sụp đổ, cấp dưới làm phản hoặc sai sót.',
      wealth: 'Thâm hụt vốn liếng, không nên vay mượn hay cho vay.',
      travel: 'Dễ bị ngã đau, trặc chân, hỏng phương tiện đi lại.',
      health: 'Đau gân cốt, gãy chân tay, thương tích phần dưới cơ thể.',
    },
    Nhâm: {
      name: 'Thanh Long Nhập Lao (Rồng Vào Lưới Nước)',
      nature: 'Hung',
      poem: 'Mậu gia Nhâm hề nhập thiên lao, quan tụng triền miên sự bất hào.',
      meaning: 'Mậu Thổ chìm vào Nhâm Thủy ngập lụt. Âm dương đảo lộn, mưu sự bất toại.',
      career: 'Công việc chìm nổi vô định, nhiều áp lực bủa vây.',
      wealth: 'Tiền bạc trôi dạt, hao tán vì việc bên ngoài.',
      travel: 'Tránh vùng sông nước bão lụt, đề phòng đuối nước.',
      health: 'Bệnh thận, bàng quang, phù nề ứ nước.',
    },
    Quý: {
      name: 'Thanh Long Hoa Cái (Thiên Ất Hội Hợp)',
      nature: 'Cát',
      poem: 'Mậu Quý tương hợp hóa vi Hỏa, mưu sự hòa hợp phúc lộc đa.',
      meaning: 'Mậu Quý tương hợp hóa Hỏa. Lợi cho cầu phúc, việc cưới hỏi, gặp gỡ giao tế.',
      career: 'Được quý nhân nâng đỡ, kết giao minh hữu.',
      wealth: 'Kinh doanh phát tài nhờ mạng lưới quan hệ rộng.',
      travel: 'Xuất hành hòa hợp, gặp nhiều duyên lành.',
      health: 'Sức khỏe tốt, tinh thần thoải mái, tai qua nạn khỏi.',
    },
  },

  Ất: {
    Mậu: {
      name: 'Lợi Âm Hại Dương (Ất gia Mậu)',
      nature: 'Bình Hòa',
      poem: 'Ất gia Mậu hề lợi âm nhân, môn chế môn sinh định cát hung.',
      meaning: 'Âm Mộc khắc Dương Thổ. Lợi cho phụ nữ, người ở ẩn, mưu việc kín đáo.',
      career: 'Nên làm việc hậu trường, cố vấn, không nên đứng đầu xuất đầu lộ diện.',
      wealth: 'Tài lộc bình ổn qua các kênh đầu tư an toàn.',
      travel: 'Xuất hành bình thường, cần xem thêm Cửa và Sao.',
      health: 'Bệnh gan mật khí trệ, nên tĩnh dưỡng.',
    },
    Ất: {
      name: 'Nhật Kỳ Phục Ngâm',
      nature: 'Hung',
      poem: 'Ất gia Ất hề phục ngâm cách, bất nghi kiến quý mưu sự trệ.',
      meaning: 'Nhật kỳ trùng điệp, mây mù che khuất mặt trời. Không lợi cầu quan yết kiến quý nhân.',
      career: 'Tiến thoái lưỡng nan, dậm chân tại chỗ, mưu việc bất thành.',
      wealth: 'Giữ chặt tiền bạc, không mạo hiểm đầu tư.',
      travel: 'Xuất hành bị chậm trễ kéo dài thời gian.',
      health: 'Bệnh mãn tính dai dẳng chưa dứt điểm.',
    },
    Bính: {
      name: 'Kỳ Nghi Thuận Toại (Nhật Nguyệt Tinh Hành)',
      nature: 'Đại Cát',
      poem: 'Ất gia Bính hề thuận toại hanh, cát tinh cao chiếu phúc lộc sinh.',
      meaning: 'Mộc sinh Hỏa, Mộc Hỏa thông minh. Nhật Nguyệt cùng soi chiếu rực rỡ.',
      career: 'Thi cử đỗ đầu, thăng quan vinh hiển, văn võ song toàn.',
      wealth: 'Lợi nhuận dồi dào, kinh doanh phát đạt nhanh chóng.',
      travel: 'Xuất hành gặp đại quý nhân, đường đi hanh thông rộng mở.',
      health: 'Thể lực sung mãn, bệnh tật tiêu tan.',
    },
    Đinh: {
      name: 'Kỳ Nghi Tương Tả (Ngọc Nữ Thừa Vân)',
      nature: 'Đại Cát',
      poem: 'Ất gia Đinh hề tương tá vinh, văn thư chiếu chỉ tứ phương minh.',
      meaning: 'Âm Mộc sinh Âm Hỏa, Tú khí phát lộ. Vô cùng lợi cho văn bằng, chức vị, giấy tờ.',
      career: 'Nhận quyết định thăng chức, ký kết hợp đồng lớn, đỗ đạt bảng vàng.',
      wealth: 'Phát tài qua văn hóa, trí tuệ, bản quyền, thương hiệu.',
      travel: 'Đi xa gặp may mắn, có tin vui từ phương xa gửi về.',
      health: 'Tâm trí sáng suốt, khí huyết điều hòa.',
    },
    Kỷ: {
      name: 'Nhật Kỳ Nhập Vụ (Uất Thần Cách)',
      nature: 'Hung',
      poem: 'Ất gia Kỷ hề vụ khí thâm, gian tà mưu hại họa tiềm trầm.',
      meaning: 'Cây cỏ mọc trên đất ẩm u tối, bị sương mù che lấp. Đề phòng tiểu nhân lừa gạt.',
      career: 'Bị hãm hại sau lưng, danh dự bị tổn thương vì tin đồn.',
      wealth: 'Dễ bị thâm hụt tiền bạc do người thân quen làm hao tổn.',
      travel: 'Xuất hành cẩn thận mất cắp hành lý, lừa gạt.',
      health: 'Bệnh phong thấp, đau nhức xương khớp, tỳ vị yếu.',
    },
    Canh: {
      name: 'Nhật Kỳ Bị Hình (Thái Bạch Hợp Kỳ)',
      nature: 'Hung',
      poem: 'Ất gia Canh hề thụ hình thương, phu phụ tương khắc sự đa mang.',
      meaning: 'Ất Canh tuy hợp nhưng Kim khắc Mộc. Vợ chồng bất hòa, kiện tụng liên miên.',
      career: 'Hợp tác rạn nứt, tranh chấp quyền lực nội bộ.',
      wealth: 'Bị đối tác chèn ép phân chia lợi nhuận không đều.',
      travel: 'Đi đường dễ gặp sự cố va chạm tranh chấp.',
      health: 'Đề phòng thương tích do kim khí kim loại, đau mắt.',
    },
    Tân: {
      name: 'Thanh Long Đào Tẩu (Rồng Xanh Chạy Trốn)',
      nature: 'Đại Hung',
      poem: 'Ất gia Tân hề Long đào tẩu, gia bại nhân vong lục súc tẩu.',
      meaning: 'Tân Kim âm sát chặt đứt rễ Ất Mộc. Cách cục đại hung, tai ương bất ngờ, phá tán.',
      career: 'Mất chức, bị sa thải, công ty phá sản, danh tiếng tiêu tan.',
      wealth: 'Phá tài nặng nề, nợ nần bủa vây, tiền mất tật mang.',
      travel: 'Kỵ xuất hành, dễ gặp nguy hiểm tính mạng hoặc mất tài sản.',
      health: 'Bệnh gan mật nguy kịch, chấn thương đổ máu.',
    },
    Nhâm: {
      name: 'Nhật Kỳ Nhập Địa (Mộc Chìm Dưới Nước)',
      nature: 'Hung',
      poem: 'Ất gia Nhâm hề nhập địa trung, nô tỳ phi phản họa bất cùng.',
      meaning: 'Thủy nhiều Mộc trôi dạt. Người dưới quyền làm phản, gia đình xáo trộn.',
      career: 'Cấp dưới phản bội làm hỏng việc lớn, mất uy tín.',
      wealth: 'Tiền bạc trôi dạt khó giữ, cho vay không đòi được.',
      travel: 'Xuất hành gặp mưa bão trắc trở.',
      health: 'Bệnh thận, bàng quang, ứ trệ phù thũng.',
    },
    Quý: {
      name: 'Hoa Cái Bồng Tinh (Kỳ Nhập Thái Âm)',
      nature: 'Cát',
      poem: 'Ất gia Quý hề hoa cái sinh, ẩn tích tàng hình tu đạo thành.',
      meaning: 'Mưa nhuần tưới cỏ cây. Rất lợi cho việc tu dưỡng học tập, ẩn dật, chữa bệnh, thiền định.',
      career: 'Thích hợp nghiên cứu chuyên sâu, hoạch định chiến lược kín đáo.',
      wealth: 'Tài lộc thầm lặng, tích lũy vững chắc.',
      travel: 'Đi xa tìm thầy học đạo, du lịch nghỉ dưỡng rất tốt.',
      health: 'Bệnh tật tiêu trừ nhờ thuốc nam thảo dược.',
    },
  },

  Bính: {
    Mậu: {
      name: 'Phi Điệp Điệt Huyệt (Chim Bay Về Tổ)',
      nature: 'Đại Cát',
      poem: 'Bính gia Mậu hề điệp điệt huyệt, bách sự thông hanh giai hỷ duyệt.',
      meaning: 'Đệ nhất Cát cách ngang Thanh Long Phản Thủ. Lửa mặt trời ấm đất, mưu sự đại thành.',
      career: 'Thăng quan cực nhanh, ngồi vào vị trí cao nhất, công danh viên mãn.',
      wealth: 'Đắc tài đại lợi, mua nhà đất bất động sản siêu lợi nhuận.',
      travel: 'Đi xa trở về mang đầy vinh quang và tiền của.',
      health: 'Bệnh tật mau lành, cơ thể khang kiện trường thọ.',
    },
    Ất: {
      name: 'Nhật Nguyệt Tinh Hành (Tước Hàm Hoa)',
      nature: 'Đại Cát',
      poem: 'Bính gia Ất hề Tước hàm hoa, quý nhân tương trợ phúc vạn gia.',
      meaning: 'Chim sẻ ngậm hoa mang tin vui đến. Quý nhân nâng đỡ, tài lộc dồi dào.',
      career: 'Được đề bạt vượt cấp, tiếng tăm vang dội tứ phương.',
      wealth: 'Tiền tài đến nhẹ nhàng thuận lợi qua các mối quan hệ quý giá.',
      travel: 'Xuất hành ngập tràn niềm vui, gặp bạn hiền tri kỷ.',
      health: 'Khí sắc hồng hào, sức khỏe an khang.',
    },
    Bính: {
      name: 'Nguyệt Kỳ Bột Soái (Hỏa Đa Hỏa Tức)',
      nature: 'Hung',
      poem: 'Bính gia Bính hề bột soái liên, văn thư trục trặc thị phi triền.',
      meaning: 'Hai Bính hừng hực quá nóng sinh bốc đồng, cãi vã, văn thư sai sót.',
      career: 'Tranh chấp với cấp trên, đồng nghiệp bất hòa do nóng nảy.',
      wealth: 'Chi tiêu bừa bãi do cảm xúc nhất thời, hao tổn.',
      travel: 'Dễ va chạm nóng giận trên đường.',
      health: 'Bệnh tim mạch, tăng huyết áp, viêm nhiệt bốc hỏa.',
    },
    Đinh: {
      name: 'Tinh Kỳ Chu Tước (Thiên Độn Cát Cách)',
      nature: 'Đại Cát',
      poem: 'Bính gia Đinh hề Chu Tước tường, quý nhân đề bạt tiến gia trang.',
      meaning: 'Mặt trời cùng vì sao tương trợ, ánh sáng chan hòa khắp nơi.',
      career: 'Thi cử đỗ tiến sĩ, thăng quan nhanh chóng, ký kết hợp đồng hoàn hảo.',
      wealth: 'Phát tài lớn từ kinh doanh, thương mại, truyền thông.',
      travel: 'Xuất hành trăm ngả đều gặp may.',
      health: 'Sức khỏe dồi dào, tinh thần minh mẫn.',
    },
    Kỷ: {
      name: 'Thái Bột Nhập Hình (Hỏa Rơi Vào Mương)',
      nature: 'Hung',
      poem: 'Bính gia Kỷ hề nhập hình thương, tù ngục oan khiên sự nan lường.',
      meaning: 'Lửa Bính rơi vào đất Kỷ thành khói mù. Đề phòng phạm pháp, kiện cáo, tù tội.',
      career: 'Bị cấp dưới liên lụy, thanh tra kiểm tra gặp rắc rối.',
      wealth: 'Tài chính mập mờ dễ bị phạt vạ thu hồi tài sản.',
      travel: 'Tránh xa nơi tranh chấp đánh nhau.',
      health: 'Bệnh đường ruột tỳ vị, đau mắt, sốt cao.',
    },
    Canh: {
      name: 'Huỳnh Hoặc Nhập Bạch (Bính gia Canh)',
      nature: 'Cát',
      poem: 'Bính gia Canh hề Huỳnh nhập Bạch, đạo tặc thối tẩu tặc tự diệt.',
      meaning: 'Hỏa khắc Kim, giặc cướp thấy lửa sợ hãi tự rút lui. Chủ sự việc nhanh chóng được giải quyết.',
      career: 'Đánh bại đối thủ cạnh tranh, giành thế chủ động hoàn toàn.',
      wealth: 'Đòi được nợ khó đòi, bảo toàn được vốn liếng.',
      travel: 'Xuất hành áp đảo được gian tà, an toàn tuyệt đối.',
      health: 'Bệnh tật được chặn đứng kịp thời.',
    },
    Tân: {
      name: 'Mưu Sự Tựu Thành (Bính Tân Tương Hợp)',
      nature: 'Cát',
      poem: 'Bính gia Tân hề sự tựu thành, âm dương hợp đức lộc tài sinh.',
      meaning: 'Bính Tân hóa Thủy tương hợp. Mưu việc dễ thành, hôn nhân tốt đẹp.',
      career: 'Hợp tác thành công, đối tác tin cậy, đôi bên cùng có lợi.',
      wealth: 'Tài lộc sinh sôi qua việc kinh doanh đôi bên.',
      travel: 'Xuất hành gặp nhân duyên tốt lành.',
      health: 'Bệnh tật mau khỏi, âm dương quân bình.',
    },
    Nhâm: {
      name: 'Hỏa Nhập Thiên La (Nhật Chiếu Thiên Nhai)',
      nature: 'Hung',
      poem: 'Bính gia Nhâm hề Hỏa nhập La, quan phi khẩu thiệt họa phi ma.',
      meaning: 'Lửa mặt trời chìm xuống biển sâu. Kiện cáo thị phi, thị phi bủa vây.',
      career: 'Bị gièm pha sau lưng, công việc đình trệ bất minh.',
      wealth: 'Tiền bạc hao tán vào kiện tụng hoặc tranh chấp.',
      travel: 'Tránh đi sông nước, đề phòng tai nạn đường thủy.',
      health: 'Bệnh tim thận bất giao, mất ngủ suy nhược.',
    },
    Quý: {
      name: 'Hoa Cái Bột Soái (Mưa Che Mặt Trời)',
      nature: 'Hung',
      poem: 'Bính gia Quý hề âm vụ già, quý nhân bất trợ sự nan tha.',
      meaning: 'Mưa mù mịt che khuất ánh mặt trời. Mưu việc nửa vời, bị quý nhân cản trở.',
      career: 'Cấp trên thay đổi ý định làm hỏng kế hoạch.',
      wealth: 'Dễ bị lừa dối trong các giao dịch ngầm.',
      travel: 'Đi đường gặp mưa gió trắc trở trì hoãn.',
      health: 'Bệnh mắt, đau đầu, khí huyết kém lưu thông.',
    },
  },

  Đinh: {
    Mậu: {
      name: 'Thanh Long Chuyển Quang',
      nature: 'Đại Cát',
      poem: 'Đinh gia Mậu hề quang chuyển huy, quan cao chức trọng đắc thời quy.',
      meaning: 'Đinh Hỏa gặp Mậu Thổ sinh quang rực rỡ. Người hèn hóa sang, người nghèo thành giàu.',
      career: 'Được cất nhắc lên vị trí lãnh đạo, quyền uy tăng vọt.',
      wealth: 'Lợi nhuận khổng lồ từ các thương vụ lớn.',
      travel: 'Xuất hành gặp quý nhân quyền quý đón rước.',
      health: 'Sức khỏe kiện khang, trường thọ an khang.',
    },
    Ất: {
      name: 'Ngọc Nữ Thừa Vân (Nhân Độn Cách)',
      nature: 'Đại Cát',
      poem: 'Đinh gia Ất hề Ngọc nữ tường, hôn nhân hòa mỹ sự cát xương.',
      meaning: 'Cây cỏ nuôi dưỡng ngọn lửa Đinh lung linh. Cực tốt cho thi cử, hôn nhân, danh tiếng.',
      career: 'Đỗ đạt thủ khoa, nhận học bổng danh giá, ký hợp đồng lớn.',
      wealth: 'Tài lộc dồi dào, gia đạo hưng thịnh giàu có.',
      travel: 'Đi xa tìm được cơ hội đổi đời.',
      health: 'Tinh thần sảng khoái, không lo bệnh tật.',
    },
    Bính: {
      name: 'Tinh Tùy Nguyệt Chuyển (Quý Nhân Thăng Điện)',
      nature: 'Cát',
      poem: 'Đinh gia Bính hề Tinh tùy Nguyệt, bách sự hanh thông hỷ tương tiếp.',
      meaning: 'Sao nhỏ nương nhờ ánh trăng mặt trời. Nhờ uy tín người lớn mà thành việc lớn.',
      career: 'Dựa vào cây cao bóng cả mà thăng tiến vùn vụt.',
      wealth: 'Đầu tư ăn theo các tập đoàn lớn thắng lớn.',
      travel: 'Đi theo đoàn lớn an toàn đắc lợi.',
      health: 'Sức khỏe ổn định, bệnh tật tiêu trừ.',
    },
    Đinh: {
      name: 'Kỳ Nhập Thái Âm (Đinh gia Đinh)',
      nature: 'Đại Cát',
      poem: 'Đinh gia Đinh hề nhập Thái Âm, văn thư toại ý vạn phúc thâm.',
      meaning: 'Hai Đinh trùng phùng âm hỏa tương trợ. Văn thư chiếu chỉ như ý muốn.',
      career: 'Nhận thư mời làm việc cao cấp, quyết định bổ nhiệm chính thức.',
      wealth: 'Tiền bạc về đều đặn, tài sản gia tăng vững bền.',
      travel: 'Xuất hành bình an, gặp nhiều tin vui thuận lợi.',
      health: 'Tâm an thân lạc, bệnh tật lui dần.',
    },
    Kỷ: {
      name: 'Hỏa Nhập Câu Trận (Chu Tước Nhập Mộ)',
      nature: 'Hung',
      poem: 'Đinh gia Kỷ hề Chu Tước trĩ, gian tà mưu hại sự nan thành.',
      meaning: 'Lửa Đinh bị đất Kỷ vùi lấp. Giấy tờ sai lệch, gian tà lừa gạt sau lưng.',
      career: 'Văn thư bị thất lạc hoặc chậm trễ làm hỏng việc quan trọng.',
      wealth: 'Thất thoát tiền bạc do tin nhầm người.',
      travel: 'Đề phòng mất hộ chiếu giấy tờ tùy thân khi đi xa.',
      health: 'Bệnh tim hồi hộp, suy nhược thần kinh.',
    },
    Canh: {
      name: 'Đình Đình Cách (Canh Cách Khẩu Thiệt)',
      nature: 'Hung',
      poem: 'Đinh gia Canh hề sự tranh phong, khẩu thiệt thị phi họa bất cùng.',
      meaning: 'Đinh Hỏa rèn Canh Kim sinh khói lửa tranh giành. Tranh chấp tài sản kiện tụng.',
      career: 'Tranh giành chức vụ nội bộ kịch liệt.',
      wealth: 'Chia chác tài sản không đều sinh thù oán.',
      travel: 'Dễ cãi vã với người cùng đi trên đường.',
      health: 'Đề phòng đứt tay chân, thương tích kim loại.',
    },
    Tân: {
      name: 'Chu Tước Nhập Ngục (Tội Nhân Thích Phóng)',
      nature: 'Bình Hòa',
      poem: 'Đinh gia Tân hề nhập ngục trung, tội nhân đắc thích thứ dân ưu.',
      meaning: 'Đinh khắc Tân Kim. Người có tội được tha thứ, người ngay phải cẩn trọng giữ mình.',
      career: 'Gặp biến động cơ cấu, người cũ đi người mới đến.',
      wealth: 'Chi tiêu giải quyết các sự cố pháp lý tồn đọng.',
      travel: 'Xuất hành nên kín tiếng, không khoe khoang.',
      health: 'Bệnh phổi phế quản, ho hen kéo dài.',
    },
    Nhâm: {
      name: 'Ngũ Thần Hóa Hợp (Đinh Nhâm Hóa Mộc)',
      nature: 'Đại Cát',
      poem: 'Đinh gia Nhâm hề Hóa hợp thông, tài quan song mỹ thế vô song.',
      meaning: 'Đinh Nhâm hóa Mộc, âm dương chính hợp. Quan vận tài vận cả hai đều rạng rỡ.',
      career: 'Ký kết đại hợp đồng, thăng chức lãnh đạo cao cấp.',
      wealth: 'Tài chính vững mạnh, buôn bán sinh lời gấp bội.',
      travel: 'Xuất hành trăm sự viên mãn, gia đạo hân hoan.',
      health: 'Khí huyết lưu thông, sức khỏe tuyệt vời.',
    },
    Quý: {
      name: 'Chu Tước Đầu Giang (Chim Lao Xuống Sông)',
      nature: 'Đại Hung',
      poem: 'Đinh gia Quý hề Chu Tước trầm, văn thư tiêu hủy họa đa thâm.',
      meaning: 'Quý Thủy dội tắt Đinh Hỏa. Giấy tờ hợp đồng bị hủy, thi cử thất bại, thị phi ngập đầu.',
      career: 'Mất chức, bị hủy hợp đồng đột ngột, tiếng xấu đồn xa.',
      wealth: 'Phá sản, mất trắng tài sản trong chớp mắt.',
      travel: 'Tuyệt đối kỵ xuất hành, đề phòng đuối nước tai nạn.',
      health: 'Bệnh tim đột quỵ, sốt cao mê sảng, nguy hiểm.',
    },
  },

  Kỷ: {
    Mậu: {
      name: 'Khuyển Ngộ Thanh Long',
      nature: 'Cát',
      poem: 'Kỷ gia Mậu hề Khuyển ngộ Long, mưu sự đắc lợi hỷ trùng trùng.',
      meaning: 'Kỷ Thổ gặp Mậu Thổ được rồng nâng đỡ. Nhờ bề trên mà lập nên sự nghiệp.',
      career: 'Được sếp lớn bao bọc bảo vệ, có cơ hội thăng tiến.',
      wealth: 'Hợp tác kiếm tiền thuận lợi, có quý nhân chỉ đường.',
      travel: 'Xuất hành gặp người nâng đỡ giúp sức.',
      health: 'Sức khỏe tốt, bệnh cũ thuyên giảm.',
    },
    Ất: {
      name: 'Mộ Thần Bất Minh (Địa Hộ Phùng Tà)',
      nature: 'Hung',
      poem: 'Kỷ gia Ất hề Mộ thần xâm, gian tà ám hại họa trầm trầm.',
      meaning: 'Kỷ Thổ âm u chôn vùi Ất Mộc. Ma quỷ quấy phá, tiểu nhân hãm hại.',
      career: 'Công việc ám muội mờ mịt, bị đâm sau lưng.',
      wealth: 'Tài chính mập mờ, dễ dính líu đến tiền đen.',
      travel: 'Không nên đi đêm một mình nơi vắng vẻ.',
      health: 'Bệnh tâm linh, ác mộng, suy nhược tinh thần.',
    },
    Bính: {
      name: 'Hỏa Bột Địa Hộ',
      nature: 'Hung',
      poem: 'Kỷ gia Bính hề Hỏa bột sinh, điên đảo thị phi sự nan bình.',
      meaning: 'Lửa Bính đốt cháy đất ẩm sinh khói độc. Oan ức cãi vã, kiện tụng không ngớt.',
      career: 'Bị cấp trên hiểu lầm gay gắt, kỷ luật oan uổng.',
      wealth: 'Hao tiền tốn của giải quyết chuyện thị phi.',
      travel: 'Dễ gặp kẻ gây gổ trên đường.',
      health: 'Bệnh đau mắt đỏ, sốt viêm nhiễm.',
    },
    Đinh: {
      name: 'Chu Tước Nhập Mộ (Kỷ gia Đinh)',
      nature: 'Bình Hòa',
      poem: 'Kỷ gia Đinh hề Chu Tước mộ, văn thư tiên nan hậu đắc lộ.',
      meaning: 'Văn thư ban đầu trắc trở, sau đó mới hanh thông nhờ người âm phù hộ.',
      career: 'Thủ tục hành chính phải làm 2 lần mới xong.',
      wealth: 'Tài lộc đến chậm nhưng chắc chắn.',
      travel: 'Xuất hành túc tắc, không nên nóng vội.',
      health: 'Bệnh tim mạch ổn định dần.',
    },
    Kỷ: {
      name: 'Địa Hộ Phùng Quỷ (Phục Ngâm Kỷ)',
      nature: 'Đại Hung',
      poem: 'Kỷ gia Kỷ hề Phùng quỷ sầu, bách sự giai hung khổ nan hưu.',
      meaning: 'Hai Kỷ âm Thổ trùng điệp là cửa Địa ngục mở. Mọi sự đều bế tắc, ma quỷ lộng hành.',
      career: 'Công danh tiêu tan, bị kẻ xấu kéo bè kết cánh hãm hại.',
      wealth: 'Thâm hụt tài sản nặng nề, nợ nần khó đòi.',
      travel: 'Tuyệt đối kỵ đi xa, dễ gặp cướp hoặc tai nạn.',
      health: 'Bệnh nặng nguy hiểm, cần cầu an giải hạn.',
    },
    Canh: {
      name: 'Lợi Cách Phản Danh (Kỷ gia Canh)',
      nature: 'Hung',
      poem: 'Kỷ gia Canh hề Hình cách lai, mưu sự phản phúc hoạ sinh tai.',
      meaning: 'Kỷ sinh Canh sát khí quá nặng. Lòng tốt bị phản bội, làm ơn mắc oán.',
      career: 'Giúp đỡ đồng nghiệp bị họ cướp công trắng trợn.',
      wealth: 'Cho vay tiền bị quỵt nợ còn mang tiếng xấu.',
      travel: 'Đi đường cẩn thận va chạm gây gổ.',
      health: 'Đau gân cốt, trặc khớp.',
    },
    Tân: {
      name: 'Du Hồn Nhập Pháp (Kỷ gia Tân)',
      nature: 'Hung',
      poem: 'Kỷ gia Tân hề Du hồn kinh, quỷ mị xâm lăng sự bất minh.',
      meaning: 'Âm Thổ sinh âm Kim âm khí cực thịnh. Hoảng loạn tinh thần, quỷ ám.',
      career: 'Làm việc mất tập trung, sai sót nghiệp vụ nghiêm trọng.',
      wealth: 'Chi tiêu vô bổ vào những việc vô nghĩa.',
      travel: 'Tránh xa nghĩa địa, nhà hoang khi xuất hành.',
      health: 'Trầm cảm, mất ngủ kinh niên, hoang tưởng.',
    },
    Nhâm: {
      name: 'Địa Cương Cao Trương (Kỷ gia Nhâm)',
      nature: 'Hung',
      poem: 'Kỷ gia Nhâm hề võng trương khai, gian dâm bại lộ họa liền tai.',
      meaning: 'Đất lở vào nước sinh bùn lầy dơ bẩn. Chuyện dâm ô bại lộ, tù tội.',
      career: 'Bê bối đời tư làm tiêu tan toàn bộ sự nghiệp.',
      wealth: 'Tống tiền, tống tài, mất mát vì tình cảm mờ ám.',
      travel: 'Đề phòng cạm bẫy lừa đảo tình tiền trên đường.',
      health: 'Bệnh đường tiết niệu, sinh dục.',
    },
    Quý: {
      name: 'Địa Hình Huyền Vũ (Kỷ gia Quý)',
      nature: 'Hung',
      poem: 'Kỷ gia Quý hề Huyền Vũ trộm, khẩu thiệt hình thương sự nan tồn.',
      meaning: 'Kỷ Quý âm trọc kết hợp. Đạo tặc trộm cắp, tù ngục, kiện cáo liên miên.',
      career: 'Bị thanh tra tố cáo vi phạm pháp luật.',
      wealth: 'Trộm cắp khoắng sạch tài sản, cướp giật.',
      travel: 'Cẩn thận mất ví tiền tài sản khi ra ngoài.',
      health: 'Bệnh phụ khoa, thận suy, phù thũng.',
    },
  },

  Canh: {
    Mậu: {
      name: 'Thiên Ất Phục Cung (Thái Bạch Phục Cung)',
      nature: 'Đại Hung',
      poem: 'Canh gia Mậu hề Phục cung sầu, tài sản tiêu tán sự nan cầu.',
      meaning: 'Canh Kim sát đánh thẳng vào Mậu Thổ bản cung. Phá sản, đổi chủ, tai ương ập đến.',
      career: 'Mất chức, bị sa thải, công ty giải thể phá sản.',
      wealth: 'Mất mát tài sản lớn, nhà đất bị tịch thu kê biên.',
      travel: 'Kỵ xuất hành, xe cộ hỏng hóc giữa đường.',
      health: 'Bệnh nan y nguy kịch, đổ máu cấp cứu.',
    },
    Ất: {
      name: 'Thái Bạch Bồng Tinh (Ất Canh Tương Hợp)',
      nature: 'Cát',
      poem: 'Canh gia Ất hề Bồng tinh tường, thối thủ đắc an tiến tất thương.',
      meaning: 'Canh hợp Ất Mộc hóa hung thành cát nếu lui về giữ mình, tiến lên sẽ bị thương.',
      career: 'Nên phòng thủ, hòa giải với đối thủ cạnh tranh.',
      wealth: 'Thu hồi công nợ êm đẹp, chia sẻ lợi ích hài hòa.',
      travel: 'Xuất hành bình yên nếu không tham lam.',
      health: 'Bệnh tình ổn định.',
    },
    Bính: {
      name: 'Thái Bạch Nhập Huỳnh Hoặc (Bạch Nhập Huỳnh)',
      nature: 'Hung',
      poem: 'Canh gia Bính hề tặc tất lai, đề phòng đạo tặc họa sinh tai.',
      meaning: 'Canh Kim xâm phạm Bính Hỏa. Giặc cướp kéo đến, bị tấn công bất ngờ.',
      career: 'Bị đối thủ chơi xấu, tấn công thị trường bất thình lình.',
      wealth: 'Phòng ngừa trộm cắp đột nhập nhà cửa, lừa đảo công nghệ cao.',
      travel: 'Đi xa đề phòng cướp giật trên đường.',
      health: 'Sốt cao, tai nạn bất ngờ do va chạm xe cộ.',
    },
    Đinh: {
      name: 'Đình Đình Chi Cách (Canh gia Đinh)',
      nature: 'Hung',
      poem: 'Canh gia Đinh hề khẩu thiệt đa, nhân tình tư sắc họa phi ma.',
      meaning: 'Canh Đinh tương khắc sinh thị phi tình ái. Đàn ông vì gái mà mất chức mất tiền.',
      career: 'Scandal tình cảm làm hỏng sự nghiệp chính trị.',
      wealth: 'Hao tốn tiền bạc vì nhân tình, bồ nhí.',
      travel: 'Tránh xa chốn ăn chơi trác táng khi đi xa.',
      health: 'Bệnh tim mạch, bệnh lây truyền.',
    },
    Kỷ: {
      name: 'Hình Cách (Canh gia Kỷ)',
      nature: 'Đại Hung',
      poem: 'Canh gia Kỷ hề quan phi lai, hình ngục tương triền bách sự tai.',
      meaning: 'Canh Kim gặp Kỷ Thổ bị chôn vùi sinh oán khí. Tù tội kiện tụng đẫm máu.',
      career: 'Bị khởi tố, vào tù ra tội, cách chức truy tố.',
      wealth: 'Bị phạt tiền nặng nề, phong tỏa toàn bộ tài khoản.',
      travel: 'Kỵ xuất hành, dễ dính líu pháp luật công an bắt giữ.',
      health: 'Thương tích nặng nề, mổ xẻ phẫu thuật.',
    },
    Canh: {
      name: 'Thái Bạch Đồng Cung (Chiến Cách)',
      nature: 'Đại Hung',
      poem: 'Canh gia Canh hề Huynh đệ tranh, quan phi đạo tặc sự bất hanh.',
      meaning: 'Hai Canh Kim đại sát đâm chém nhau. Huynh đệ tương tàn, chiến tranh đẫm máu.',
      career: 'Nội bộ tranh quyền thanh trừng lẫn nhau khốc liệt.',
      wealth: 'Tranh chấp di sản đổ máu, phá sản sạch sành sanh.',
      travel: 'Tuyệt đối kỵ xuất hành, dễ gặp bạo lực xung đột vũ trang.',
      health: 'Tai nạn gãy xương, đâm chém thương vong.',
    },
    Tân: {
      name: 'Bạch Hổ Can Cách (Canh gia Tân)',
      nature: 'Đại Hung',
      poem: 'Canh gia Tân hề Can cách hung, viễn hành thất mê sự bất dung.',
      meaning: 'Hai thứ Kim âm dương cùng sát hại lẫn nhau. Đi xa lạc đường, xe cộ tai nạn thảm khốc.',
      career: 'Dự án sụp đổ toàn diện, mất sạch nguồn vốn.',
      wealth: 'Phá sản, trộm cướp lấy hết tài sản.',
      travel: 'Tuyệt đối cấm xuất hành, lỡ tàu xe gặp nạn lớn.',
      health: 'Bệnh phổi nặng, tai nạn giao thông nghiêm trọng.',
    },
    Nhâm: {
      name: 'Tiểu Cách (Canh gia Nhâm)',
      nature: 'Hung',
      poem: 'Canh gia Nhâm hề viễn hành mê, quan sự triền miên sự bất tề.',
      meaning: 'Canh Kim sinh Nhâm Thủy cuồn cuộn. Đi xa lạc lối, kiện tụng dây dưa không dứt.',
      career: 'Thay đổi chỗ làm liên tục mà không có kết quả.',
      wealth: 'Tiền bạc trôi như nước đổ lá khoai.',
      travel: 'Lạc đường, trễ chuyến, gặp rắc rối nơi đất khách.',
      health: 'Bệnh thận, suy nhược toàn thân.',
    },
    Quý: {
      name: 'Đại Cách (Canh gia Quý)',
      nature: 'Đại Hung',
      poem: 'Canh gia Quý hề Đại cách lai, quan phi hình lục thế nan hồi.',
      meaning: 'Canh Kim gặp Quý Thủy âm u. Cách cục trở ngại lớn nhất trong năm tháng ngày giờ.',
      career: 'Sự nghiệp đứt gánh giữa đường, bị giáng chức đuổi việc.',
      wealth: 'Phá tài nặng nề, làm ăn đổ bể hoàn toàn.',
      travel: 'Kỵ xuất hành trăm sự không thành.',
      health: 'Bệnh hiểm nghèo, biến chứng nguy hiểm.',
    },
  },

  Tân: {
    Mậu: {
      name: 'Khôn Long Bị Thương (Tân gia Mậu)',
      nature: 'Hung',
      poem: 'Tân gia Mậu hề Long thụ thương, quan phi khẩu thiệt sự đa mang.',
      meaning: 'Tân Kim đục khoét Mậu Thổ. Mất tiền mất của, cấp dưới làm tổn hại cấp trên.',
      career: 'Bị nhân viên dưới quyền tố cáo sai phạm.',
      wealth: 'Đầu tư thua lỗ do quản lý lỏng lẻo.',
      travel: 'Xuất hành hao tài tốn của.',
      health: 'Đau dạ dày, đau chân tay.',
    },
    Ất: {
      name: 'Bạch Hổ Xướng Cuồng (Hổ Trắng Gào Thét)',
      nature: 'Đại Hung',
      poem: 'Tân gia Ất hề Bạch Hổ cuồng, nhân vong gia bại thế nan đương.',
      meaning: 'Tân Kim chém nát Ất Mộc. Vợ chết con mất, người nhà ly tán, tai họa liên miên.',
      career: 'Sự nghiệp sụp đổ do tai họa bất ngờ ập đến.',
      wealth: 'Tài sản khánh kiệt vì biến cố gia đình.',
      travel: 'Tuyệt đối cấm xuất hành, họa sát thân.',
      health: 'Bệnh gan cấp tính, đổ máu tai nạn tử vong.',
    },
    Bính: {
      name: 'Can Hợp Bột Soái (Tân gia Bính)',
      nature: 'Cát',
      poem: 'Tân gia Bính hề Can hợp hanh, mưu sự đắc lợi hỷ khí sinh.',
      meaning: 'Bính Tân tương hợp hóa Thủy. Lợi cho mưu sự, hợp tác, giải oan, hòa giải.',
      career: 'Được quý nhân tha thứ sai lầm, phục hồi uy tín.',
      wealth: 'Thu hồi được vốn liếng đã mất.',
      travel: 'Xuất hành bình an, gặp bạn bè tương trợ.',
      health: 'Bệnh tật thuyên giảm rõ rệt.',
    },
    Đinh: {
      name: 'Ngục Thần Đắc Kỳ (Tân gia Đinh)',
      nature: 'Đại Cát',
      poem: 'Tân gia Đinh hề Ngục thần kỳ, tội nhân đắc xá bách sự nghi.',
      meaning: 'Tân Kim gặp Đinh Hỏa tôi luyện thành bảo kiếm. Tù nhân được tha, người oan được rửa sạch.',
      career: 'Vượt qua sóng gió thử thách, thăng tiến lên đỉnh cao.',
      wealth: 'Thu được nguồn lợi nhuận bất ngờ từ dự án tưởng chừng bỏ đi.',
      travel: 'Đi xa tìm được cơ hội vàng đổi đời.',
      health: 'Bệnh nan y gặp thần dược cứu sống.',
    },
    Kỷ: {
      name: 'Nhập Ngục Tự Hình (Tân gia Kỷ)',
      nature: 'Hung',
      poem: 'Tân gia Kỷ hề nhập ngục trung, tự chuốc lấy họa sự nan dung.',
      meaning: 'Tân Kim bị đất Kỷ vùi lấp. Tự mình chuốc họa, tự gây rắc rối cho bản thân.',
      career: 'Quyết định sai lầm dẫn đến mất chức.',
      wealth: 'Đầu tư mù quáng dẫn đến thua lỗ nặng.',
      travel: 'Tránh đi một mình vào nơi hiểm trở.',
      health: 'Bệnh trầm cảm, tự làm tổn thương bản thân.',
    },
    Canh: {
      name: 'Bạch Hổ Xuất Lực (Tân gia Canh)',
      nature: 'Hung',
      poem: 'Tân gia Canh hề Hổ xuất uy, chủ khách tương tranh sự bất quy.',
      meaning: 'Hai Kim tương tranh, chủ và khách đánh nhau vỡ đầu chảy máu.',
      career: 'Tranh chấp hợp đồng với đối tác phải ra tòa.',
      wealth: 'Tiền bạc bị đối tác chiếm đoạt.',
      travel: 'Gặp cướp giật đe dọa trên đường.',
      health: 'Thương tích do dao kéo, kim loại đâm chém.',
    },
    Tân: {
      name: 'Phục Ngâm Thiên Đình (Tân gia Tân)',
      nature: 'Đại Hung',
      poem: 'Tân gia Tân hề Phục ngâm sầu, tự hình tương khắc họa nan hưu.',
      meaning: 'Hai Tân âm Kim tự hình nhau. Đau khổ dằn vặt, tù tội oan khiên bế tắc.',
      career: 'Công việc bế tắc cùng cực, không lối thoát.',
      wealth: 'Phá tài do tự mình phung phí.',
      travel: 'Xuất hành bị giam giữ giữ chân.',
      health: 'Bệnh ung thư, u hạch, viêm nhiễm hoại tử.',
    },
    Nhâm: {
      name: 'Hung Xà Nhập Ngục (Tân gia Nhâm)',
      nature: 'Hung',
      poem: 'Tân gia Nhâm hề Xà nhập lao, lưỡng hổ tương tranh sự bất hào.',
      meaning: 'Kim sinh Thủy cuộn trào nhấn chìm nhau. Tranh chấp kéo dài, hai bên cùng thiệt hại.',
      career: 'Đấu đá nội bộ làm cả phòng ban bị giải tán.',
      wealth: 'Kiện cáo tốn kém cạn kiệt tài chính.',
      travel: 'Tránh xa sông biển mùa mưa bão.',
      health: 'Bệnh thận, phù phổi, tai biến.',
    },
    Quý: {
      name: 'Thiên Lao Hoa Cái (Tân gia Quý)',
      nature: 'Hung',
      poem: 'Tân gia Quý hề nhập thiên lao, nhật nguyệt vô quang dạ thảm sầu.',
      meaning: 'Tân Kim gặp Quý Thủy tối tăm mù mịt. Bị giam cầm, cô lập, không ai giúp đỡ.',
      career: 'Bị cô lập hoàn toàn tại cơ quan, mất hết quyền hành.',
      wealth: 'Tài chính đóng băng không rút được tiền.',
      travel: 'Kỵ đi xa, dễ bị kẹt lại không về được.',
      health: 'Bệnh phụ khoa, đường ruột mãn tính.',
    },
  },

  Nhâm: {
    Mậu: {
      name: 'Tiểu Xà Hóa Long (Nhâm gia Mậu)',
      nature: 'Đại Cát',
      poem: 'Nhâm gia Mậu hề Xà hóa Long, quan cao lộc hậu phúc trùng trùng.',
      meaning: 'Nước lớn gặp bờ đê vững chãi hóa thành rồng bay lên trời. Sự nghiệp phát triển rực rỡ.',
      career: 'Thăng quan cực nhanh, lập công trạng lớn được triều đình phong thưởng.',
      wealth: 'Tài lộc đại phát, mua đất đai xây dựng biệt phủ.',
      travel: 'Xuất hành đại cát đại lợi, công danh toại nguyện.',
      health: 'Khí lực dồi dào, thọ trường an khang.',
    },
    Ất: {
      name: 'Tiểu Xà Đắc Thế (Nhâm gia Ất)',
      nature: 'Cát',
      poem: 'Nhâm gia Ất hề Xà đắc thời, âm nhân trợ lực sự giai nghi.',
      meaning: 'Nước Nhâm tưới cây Ất Mộc tươi tốt. Được phụ nữ quý nhân giúp đỡ thành công.',
      career: 'Được sếp nữ hoặc đối tác nữ ưu ái tạo điều kiện.',
      wealth: 'Kinh doanh thời trang, mỹ phẩm, nghệ thuật siêu lợi nhuận.',
      travel: 'Xuất hành gặp duyên lành với nữ nhân.',
      health: 'Sức khỏe tốt, tinh thần thoải mái.',
    },
    Bính: {
      name: 'Thủy Xà Nhập Hỏa (Nhâm gia Bính)',
      nature: 'Hung',
      poem: 'Nhâm gia Bính hề Thủy Hỏa chiến, quan phi đạo tặc họa triền miên.',
      meaning: 'Thủy Hỏa tương xung kịch liệt. Tranh chấp bạo lực, thị phi kiện tụng nổ ra.',
      career: 'Bất hòa gay gắt với lãnh đạo cao nhất.',
      wealth: 'Mất tiền vì đầu tư nóng vội mạo hiểm.',
      travel: 'Đề phòng hỏa hoạn, nổ lốp xe trên đường cao tốc.',
      health: 'Bệnh tim mạch, xuất huyết não, đột quỵ.',
    },
    Đinh: {
      name: 'Can Hợp Tinh Xà (Nhâm Đinh Tương Hợp)',
      nature: 'Đại Cát',
      poem: 'Nhâm gia Đinh hề Tinh xà hợp, văn thư quý nhân tương phù trợ.',
      meaning: 'Nhâm Đinh hóa Mộc hữu tình. Ký kết hợp đồng ngầm, hôn nhân đại cát, quý nhân phù trợ.',
      career: 'Được bổ nhiệm chức vụ quan trọng một cách êm đẹp.',
      wealth: 'Phát tài lớn nhờ thông tin nội bộ quý giá.',
      travel: 'Xuất hành viên mãn, gia đạo bình an.',
      health: 'Cơ thể điều hòa, sống lâu khỏe mạnh.',
    },
    Kỷ: {
      name: 'Hung Xà Nhập Ngục (Nhâm gia Kỷ)',
      nature: 'Đại Hung',
      poem: 'Nhâm gia Kỷ hề nhập ngục tù, quan tư khẩu thiệt khổ nan hưu.',
      meaning: 'Nước Nhâm bị đất bùn Kỷ làm đục ngầu. Kiện cáo tù tội, tiền mất tật mang.',
      career: 'Bị thanh tra bắt giữ vì tội tham ô hối lộ.',
      wealth: 'Bị tịch thu toàn bộ tài sản bất minh.',
      travel: 'Tuyệt đối cấm xuất hành, công an đón đầu bắt giữ.',
      health: 'Bệnh thận nặng, bí tiểu, ngộ độc.',
    },
    Canh: {
      name: 'Thái Bạch Cầm Xà (Nhâm gia Canh)',
      nature: 'Cát',
      poem: 'Nhâm gia Canh hề Bạch cầm xà, công tư phân minh tà bất phạm.',
      meaning: 'Canh Kim chế ngự dòng nước Nhâm. Pháp luật nghiêm minh, kẻ xấu bị trừng trị.',
      career: 'Thanh lọc bộ máy, lập lại kỷ cương cơ quan thành công.',
      wealth: 'Thu hồi tài sản công minh chính đại.',
      travel: 'Xuất hành bình yên, có người bảo vệ hộ tống.',
      health: 'Bệnh tật được kiểm soát tốt.',
    },
    Tân: {
      name: 'Đằng Xà Tương Chiến (Nhâm gia Tân)',
      nature: 'Hung',
      poem: 'Nhâm gia Tân hề tương chiến thương, nữ nhân sinh sản họa nan lường.',
      meaning: 'Nhâm Thủy cuốn trôi Tân Kim. Đàn bà sinh nở khó khăn, mưu sự phản trắc.',
      career: 'Hợp đồng bị đối tác lật lọng phút chót.',
      wealth: 'Mất mát tiền của vì người thứ ba can thiệp.',
      travel: 'Đề phòng sạt lở đất đá khi đi vùng núi.',
      health: 'Phụ nữ sinh đẻ nguy hiểm, rong huyết.',
    },
    Nhâm: {
      name: 'Xà Nhập Địa La (Phục Ngâm Nhâm)',
      nature: 'Đại Hung',
      poem: 'Nhâm gia Nhâm hề Xà nhập La, viễn hành thất mê họa phi ma.',
      meaning: 'Hai Nhâm Thủy hồng thủy ngập trời. Nước ngập nhà cửa, bão lụt tai ương, trôi dạt vô định.',
      career: 'Mất phương hướng trong sự nghiệp, công ty phá sản hàng loạt.',
      wealth: 'Phá tài sạch sẽ vì thiên tai lũ lụt.',
      travel: 'Tuyệt đối cấm đi xa, dễ bị cô lập trong vùng lũ.',
      health: 'Bệnh thận hư, phù nề toàn thân, đuối nước.',
    },
    Quý: {
      name: 'Ấu Nữ Gian Dâm (Nhâm gia Quý)',
      nature: 'Hung',
      poem: 'Nhâm gia Quý hề âm khí thịnh, môn hộ bất thanh sự đa kinh.',
      meaning: 'Nhâm Quý đại thủy âm u hòa vào nhau. Gia đình dâm loạn, gia đạo suy đồi bại hoại.',
      career: 'Mất uy tín nghiêm trọng vì chuyện đời tư đồi trụy.',
      wealth: 'Hao tổn tiền của vì thói trác táng bê tha.',
      travel: 'Tránh nơi bia bọt hộp đêm khi đi công tác.',
      health: 'Bệnh lây truyền qua đường tình dục, suy tủy.',
    },
  },

  Quý: {
    Mậu: {
      name: 'Thiên Ất Hội Hợp (Quý gia Mậu)',
      nature: 'Đại Cát',
      poem: 'Quý gia Mậu hề Hội hợp hanh, cát thần tương trợ phúc lộc sinh.',
      meaning: 'Quý Mậu hóa Hỏa âm dương hòa hợp. Cực tốt cho việc cầu hôn, làm nhà, nhận chức.',
      career: 'Được toàn thể cơ quan ủng hộ ngồi vào ghế lãnh đạo.',
      wealth: 'Kinh doanh liên doanh phát tài rực rỡ.',
      travel: 'Xuất hành nghênh đón nhiều tin vui mừng.',
      health: 'Sức khỏe dồi dào, thân tâm an lạc.',
    },
    Ất: {
      name: 'Hoa Cái Bồng Tinh (Quý gia Ất)',
      nature: 'Cát',
      poem: 'Quý gia Ất hề quý nhân vinh, cầu danh đắc danh sự sự hanh.',
      meaning: 'Mưa xuân nuôi mầm cây. Rất lợi cho giới trí thức, nghệ sĩ, học giả, tu sĩ.',
      career: 'Sáng tác tác phẩm để đời, nổi tiếng trong giới học thuật.',
      wealth: 'Tài lộc đến từ nhuận bút, bản quyền, sáng chế.',
      travel: 'Đi xa tìm nguồn cảm hứng sáng tạo tuyệt vời.',
      health: 'Bệnh mãn tính lành dần.',
    },
    Bính: {
      name: 'Hoa Cái Bột Soái (Quý gia Bính)',
      nature: 'Hung',
      poem: 'Quý gia Bính hề âm dương xung, quan phi khẩu thiệt sự nan dung.',
      meaning: 'Nước Quý dập lửa Bính. Kiện tụng vì lòng đố kỵ ghen ghét lẫn nhau.',
      career: 'Bị đồng nghiệp tố cáo nặc danh, thanh tra làm phiền.',
      wealth: 'Tốn tiền thuê luật sư kiện tụng.',
      travel: 'Dễ bị hoãn chuyến bay, trục trặc xe cộ.',
      health: 'Đau mắt, suy tim, sốt phát ban.',
    },
    Đinh: {
      name: 'Đằng Xà Yêu Kiều (Quý gia Đinh)',
      nature: 'Đại Hung',
      poem: 'Quý gia Đinh hề Xà yêu kiều, hỏa hoạn quan phi họa bất liêu.',
      meaning: 'Quý Thủy khắc Đinh Hỏa sinh khói độc. Hỏa hoạn thiêu rụi nhà cửa, cháy nổ, tù ngục.',
      career: 'Cơ quan xảy ra sự cố cháy nổ hoặc scandal cực lớn.',
      wealth: 'Tài sản bị thiêu rụi hoặc mất trắng vì sự cố bất ngờ.',
      travel: 'Tuyệt đối cấm xuất hành, đề phòng tai nạn nổ bình xăng, hỏa hoạn.',
      health: 'Bỏng nặng, đau mắt mù lòa, tim ngừng đập.',
    },
    Kỷ: {
      name: 'Hoa Cái Địa Hộ (Quý gia Kỷ)',
      nature: 'Hung',
      poem: 'Quý gia Kỷ hề Địa hộ tàng, âm nhân ám hại họa đa mang.',
      meaning: 'Quý Thủy ngập đất Kỷ thành bùn lầy hôi thối. Bị kẻ tiểu nhân giấu mặt hãm hại.',
      career: 'Bị chơi xấu sau lưng không rõ nguyên nhân.',
      wealth: 'Thất thoát tiền bạc từng chút một khó kiểm soát.',
      travel: 'Xuất hành dễ bị sập bẫy lừa đảo.',
      health: 'Bệnh ngộ độc thức ăn, tiêu chảy cấp tính.',
    },
    Canh: {
      name: 'Thái Bạch Nhập Võng (Quý gia Canh)',
      nature: 'Hung',
      poem: 'Quý gia Canh hề Thái Bạch sầu, quan tụng tương triền sự bất hưu.',
      meaning: 'Kim rơi vào lưới nước Quý. Đi kiện cáo thì cả hai bên đều thua thiệt tán gia bại sản.',
      career: 'Hai phe đấu đá làm công ty tê liệt giải thể.',
      wealth: 'Tài sản bị tòa án đóng băng phục vụ điều tra.',
      travel: 'Tránh đi xa vì dễ bị tạm giữ kiểm tra hành chính.',
      health: 'Đau xương khớp, bệnh phổi ngập nước.',
    },
    Tân: {
      name: 'Cương Cái Thiên Lao (Quý gia Tân)',
      nature: 'Đại Hung',
      poem: 'Quý gia Tân hề Thiên lao hung, quan phi hình ngục thế nan dung.',
      meaning: 'Tân Kim chìm dưới đáy biển sâu. Vào tù không có ngày ra, tai họa ngập tràn.',
      career: 'Bị kết án tù, tước bỏ mọi danh hiệu chức tước.',
      wealth: 'Tán gia bại sản, nợ nần không trả nổi.',
      travel: 'Kỵ xuất hành, dễ bị bắt giữ tịch thu phương tiện.',
      health: 'Bệnh hiểm nghèo giai đoạn cuối.',
    },
    Nhâm: {
      name: 'Phục Kiến Đằng Xà (Quý gia Nhâm)',
      nature: 'Hung',
      poem: 'Quý gia Nhâm hề Xà trùng phùng, gia môn bất hòa họa trùng trùng.',
      meaning: 'Nước mưa hòa vào nước biển cuộn sóng. Gia đình cãi vã, anh em từ mặt nhau.',
      career: 'Cấp dưới không phục cấp trên, đình công nổi loạn.',
      wealth: 'Tranh chấp tài sản thừa kế trong dòng họ.',
      travel: 'Xuất hành mệt mỏi, không được việc gì.',
      health: 'Bệnh thận, suy nhược cơ thể.',
    },
    Quý: {
      name: 'Thiên Võng Tứ Trương (Thiên Cương Bách Sự Bế)',
      nature: 'Đại Hung',
      poem: 'Quý gia Quý hề Thiên võng trương, bách sự giai bế mạc vọng hành.',
      meaning: 'Lưới trời bốn bề bủa vây không lối thoát. Mọi hành động đều gặp tai họa, tốt nhất nằm yên giữ mình.',
      career: 'Bị sa thải, cấm hành nghề, sự nghiệp đóng băng hoàn toàn.',
      wealth: 'Phá tài sạch sành sanh, không nên manh động làm bất cứ việc gì.',
      travel: 'Tuyệt đối cấm xuất hành, bước chân ra cửa là gặp đại họa.',
      health: 'Bệnh nặng liệt giường, nguy cơ tử vong cao nếu vọng động.',
    },
  },
};

// -------------------------------------------------------------------------------------------------
// 2. BÁT MÔN LÂM 9 CUNG & TĨNH/ĐỘNG KHẮC ỨNG (THEO QUYỂN 4 & 5 BÍ KÍP TOÀN THƯ)
// -------------------------------------------------------------------------------------------------
export const DOOR_PALACE_MATRIX: Record<string, Record<number, DoorPalaceDetail>> = {
  'Hưu Môn': {
    1: {
      relation: 'Môn Cung Tỷ Hòa (Phục Ngâm)',
      status: 'Cát',
      description: 'Hưu Môn Thủy về Khảm 1 Thủy bản cung. Tốt cho an dưỡng, cầu quý, nghỉ ngơi, dưỡng sinh.',
      staticSign: 'Trong nhà có khách quý mang rượu thịt hoặc đồ biển đến thăm.',
      dynamicSign: 'Đi nửa dặm gặp người mặc áo đen hoặc đánh cá gánh nước ven sông.',
    },
    2: {
      relation: 'Cung Khắc Môn (Môn Chế)',
      status: 'Bình',
      description: 'Khôn Thổ khắc Hưu Thủy. Sự việc chậm trễ, mưu sự cần kiên nhẫn qua người trung gian.',
      staticSign: 'Người già trong nhà càu nhàu, có việc liên quan đến ruộng đất, mồ mả.',
      dynamicSign: 'Gặp bà lão mặc áo xám hoặc người vác cuốc đi cày.',
    },
    3: {
      relation: 'Môn Sinh Cung (Nghĩa Hòa)',
      status: 'Đại Cát',
      description: 'Hưu Thủy sinh Chấn Mộc. Đại cát lợi cầu tài, xuất hành, thăng quan, mưu việc đắc thắng.',
      staticSign: 'Nhận được thư từ báo tin mừng về con cháu hoặc công danh.',
      dynamicSign: 'Gặp người cầm cành cây xanh hoặc nghe tiếng sấm chớp, trống trận.',
    },
    4: {
      relation: 'Môn Sinh Cung',
      status: 'Đại Cát',
      description: 'Hưu Thủy sinh Tốn Mộc. Lợi cho buôn bán đường dài, văn thư, kết hôn, giao dịch.',
      staticSign: 'Có người mang hoa quả, vải vóc hoặc trà bánh đến biếu tặng.',
      dynamicSign: 'Gặp phụ nữ gánh hoa quả hoặc nghe tiếng gió thổi mạnh qua rặng tre.',
    },
    6: {
      relation: 'Cung Sinh Môn',
      status: 'Cát',
      description: 'Càn Kim sinh Hưu Thủy. Được cấp trên che chở, quý nhân ban thưởng, thăng tiến chức vị.',
      staticSign: 'Cấp trên gửi quà hoặc có lệnh điều chuyển sang vị trí an nhàn hơn.',
      dynamicSign: 'Gặp người cưỡi ngựa trắng hoặc quan chức mặc áo gấm đi xe sang.',
    },
    7: {
      relation: 'Cung Sinh Môn',
      status: 'Cát',
      description: 'Đoài Kim sinh Hưu Thủy. Lợi cho yến tiệc, ca hát, ngoại giao, ký hợp đồng vui vẻ.',
      staticSign: 'Có bạn bè rủ đi ăn nhậu, tiệc tùng vui vẻ.',
      dynamicSign: 'Gặp thiếu nữ xinh đẹp ca hát hoặc người mang đồ kim khí trang sức.',
    },
    8: {
      relation: 'Cung Khắc Môn (Môn Chế)',
      status: 'Bình',
      description: 'Cấn Thổ khắc Hưu Thủy. Cầu tài có chút trở ngại nhưng không hại lớn.',
      staticSign: 'Con cháu trong nhà lười biếng, cần đôn đốc học hành.',
      dynamicSign: 'Gặp trẻ chăn trâu hoặc người vác đá leo núi.',
    },
    9: {
      relation: 'Môn Khắc Cung (Môn Bách)',
      status: 'Hung',
      description: 'Hưu Thủy dập Ly Hỏa. Cát môn bức cung, trong cát hàm hung, cẩn thận kiện cáo bí mật.',
      staticSign: 'Trong nhà xảy ra cãi vã vì tiền bạc, bếp núc hỏng hóc.',
      dynamicSign: 'Gặp người cầm đuốc hoặc chim đỏ bay qua kêu réo rắt.',
    },
  },

  'Sinh Môn': {
    1: {
      relation: 'Môn Khắc Cung (Môn Bách)',
      status: 'Bình',
      description: 'Sinh Môn Thổ khắc Khảm Thủy. Đệ nhất Cát môn nhưng bức cung, tài lộc đến kèm chút thị phi.',
      staticSign: 'Trong nhà mua sắm đồ đạc mới nhưng bị người ngoài dèm pha.',
      dynamicSign: 'Gặp người chài lưới bị trượt chân hoặc nước sông dâng cao.',
    },
    2: {
      relation: 'Môn Cung Tỷ Hòa',
      status: 'Đại Cát',
      description: 'Sinh Thổ về Khôn Thổ. Cực tốt cho mua bán nhà đất, trồng trọt chăn nuôi, sinh con đẻ cái.',
      staticSign: 'Gia đạo bình an, phụ nữ trong nhà sinh quý tử hoặc tích lũy được nhiều vàng bạc.',
      dynamicSign: 'Gặp đàn trâu bò đông đúc hoặc nông dân gánh lúa vàng trĩu hạt.',
    },
    3: {
      relation: 'Cung Khắc Môn (Môn Chế)',
      status: 'Cát',
      description: 'Chấn Mộc khắc Sinh Thổ. Mưu sự tuy vất vả tranh đấu nhưng kết quả vẫn bội thu.',
      staticSign: 'Có dự án mới phải làm thêm giờ nhưng tiền thưởng xứng đáng.',
      dynamicSign: 'Gặp người đẵn gỗ hoặc xe chở vật liệu xây dựng chạy qua.',
    },
    4: {
      relation: 'Cung Khắc Môn (Môn Chế)',
      status: 'Cát',
      description: 'Tốn Mộc khắc Sinh Thổ. Kinh doanh xuất nhập khẩu có lời, cần cẩn thận hợp đồng.',
      staticSign: 'Người thân phương xa gửi tiền về hoặc có khách buôn đến đặt hàng.',
      dynamicSign: 'Gặp người buôn bán tơ lụa hoặc bướm bay lượn từng đàn.',
    },
    6: {
      relation: 'Môn Sinh Cung',
      status: 'Đại Cát',
      description: 'Sinh Thổ sinh Càn Kim. Đại phú đại quý, quan vận hanh thông, công thành danh toại.',
      staticSign: 'Được thăng cấp tăng lương, danh tiếng vang dội trong ngành.',
      dynamicSign: 'Gặp đoàn xe sang trọng hoặc người mặc quan phục áo vàng.',
    },
    7: {
      relation: 'Môn Sinh Cung',
      status: 'Đại Cát',
      description: 'Sinh Thổ sinh Đoài Kim. Mua bán đắt hàng, thu tiền mặt tức thì, gia đình sung túc.',
      staticSign: 'Khách hàng nườm nượp kéo đến mua sắm trả tiền mặt.',
      dynamicSign: 'Gặp người mang vàng bạc trang sức hoặc tiếng chuông khánh vang lừng.',
    },
    8: {
      relation: 'Môn Cung Tỷ Hòa (Phục Ngâm)',
      status: 'Đại Cát',
      description: 'Sinh Thổ về Cấn 8 bản cung. Vạn sự đại cát, xây dựng bất động sản trường tồn ngàn năm.',
      staticSign: 'Khởi công xây nhà, mua đất nền, tài sản tăng giá vù vù.',
      dynamicSign: 'Gặp người leo núi vác đã hoặc đàn dê béo tốt ăn cỏ ven đồi.',
    },
    9: {
      relation: 'Cung Sinh Môn',
      status: 'Đại Cát',
      description: 'Ly Hỏa sinh Sinh Thổ. Đệ nhất phát tài trong Kỳ Môn, danh lợi song thu, tài nguyên cuồn cuộn.',
      staticSign: 'Nhận được khoản tiền đầu tư cực lớn hoặc trúng số trúng thầu.',
      dynamicSign: 'Gặp người mặc áo đỏ mang lửa hoặc chim phượng hoàng ngũ sắc đậu trên cây.',
    },
  },

  'Khai Môn': {
    1: {
      relation: 'Môn Sinh Cung',
      status: 'Đại Cát',
      description: 'Khai Kim sinh Khảm Thủy. Mở mang doanh nghiệp, khai trương buôn bán, bái quan yết quý.',
      staticSign: 'Cơ quan mở chi nhánh mới hoặc nhận được giấy phép kinh doanh thuận lợi.',
      dynamicSign: 'Gặp người mang bảo kiếm hoặc thuyền chở đầy hàng cập bến.',
    },
    2: {
      relation: 'Cung Sinh Môn',
      status: 'Đại Cát',
      description: 'Khôn Thổ sinh Khai Kim. Được mẹ cha nâng đỡ, mua bán trang trại đắc lợi lớn.',
      staticSign: 'Được thừa kế đất đai hoặc nhận vốn khởi nghiệp từ gia đình.',
      dynamicSign: 'Gặp người chở đất đắp đê hoặc người mang chum vại gốm sứ.',
    },
    3: {
      relation: 'Môn Khắc Cung (Môn Bách)',
      status: 'Hung',
      description: 'Khai Kim chém Chấn Mộc. Cát môn bức cung, khởi đầu vội vàng dễ gặp tai nạn gãy đổ.',
      staticSign: 'Trong nhà có đồ gỗ bị gãy hoặc cãi vã với trưởng nam.',
      dynamicSign: 'Gặp cây đổ chắn đường hoặc người cầm cưa rìu đẵn gỗ.',
    },
    4: {
      relation: 'Môn Khắc Cung (Môn Bách)',
      status: 'Hung',
      description: 'Khai Kim phạt Tốn Mộc. Môn Bách, mở cửa hàng dễ bị phạt hành chính hoặc tranh chấp.',
      staticSign: 'Cơ quan bị thanh tra thị trường kiểm tra giấy tờ.',
      dynamicSign: 'Gặp gió lốc cuốn lá cây mù mịt hoặc tiếng kêu khóc.',
    },
    6: {
      relation: 'Môn Cung Tỷ Hòa (Phục Ngâm)',
      status: 'Đại Cát',
      description: 'Khai Kim về Càn 6 bản cung. Trưởng bối ban quyền, chính trực quang minh, vạn sự hanh thông.',
      staticSign: 'Được lãnh đạo tối cao trực tiếp giao trọng trách lớn.',
      dynamicSign: 'Gặp người râu tóc bạc phơ cưỡi ngựa trắng hoặc quan tòa áo thụng.',
    },
    7: {
      relation: 'Môn Cung Tỷ Hòa',
      status: 'Cát',
      description: 'Khai Kim hòa Đoài Kim. Mở miệng thuyết phục được người khác, ký hợp đồng ngoại giao lớn.',
      staticSign: 'Đàm phán thắng lợi vẻ vang, các bên vui vẻ cụng ly.',
      dynamicSign: 'Gặp đoàn nghệ thuật biểu diễn hoặc người bán nhạc cụ.',
    },
    8: {
      relation: 'Cung Sinh Môn',
      status: 'Đại Cát',
      description: 'Cấn Thổ sinh Khai Kim. Khai sơn phá thạch, mở mỏ khai khoáng, xây dựng trung tâm thương mại.',
      staticSign: 'Tìm được mặt bằng kinh doanh đắc địa giá hời.',
      dynamicSign: 'Gặp người gánh đá hoặc đoàn rước dâu linh đình.',
    },
    9: {
      relation: 'Cung Khắc Môn (Môn Chế)',
      status: 'Bình',
      description: 'Ly Hỏa nung Khai Kim. Mở cửa hàng chịu áp lực thuế má, cạnh tranh khốc liệt.',
      staticSign: 'Hóa đơn tiền điện tăng vọt, máy móc nóng hỏng.',
      dynamicSign: 'Gặp thợ rèn đang đập sắt đỏ rực hoặc tiếng còi cứu hỏa.',
    },
  },

  'Thương Môn': {
    1: {
      relation: 'Cung Sinh Môn',
      status: 'Bình',
      description: 'Khảm Thủy sinh Thương Mộc. Lợi cho việc đòi nợ, săn bắn, đánh bắt thủy sản, bắt kẻ trộm.',
      staticSign: 'Có người đến đòi nợ hoặc phát hiện thất thoát hàng tồn kho.',
      dynamicSign: 'Gặp người mang cần câu cá hoặc chó săn đuổi thú.',
    },
    2: {
      relation: 'Môn Khắc Cung (Môn Bách)',
      status: 'Đại Hung',
      description: 'Thương Mộc đâm thủng Khôn Thổ. Đại hung, tai nạn giao thông đổ máu, người già bệnh nặng.',
      staticSign: 'Người già trong nhà ngã bệnh nặng hoặc tường rào bị sập.',
      dynamicSign: 'Gặp tai nạn xe cộ đâm nhau hoặc cáng cứu thương chạy qua.',
    },
    3: {
      relation: 'Môn Cung Tỷ Hòa (Phục Ngâm)',
      status: 'Hung',
      description: 'Thương Mộc về Chấn 3 bản cung. Hung môn phục ngâm, cãi cọ đánh lộn, kiện tụng đòi bồi thường.',
      staticSign: 'Anh em trong nhà mâu thuẫn đánh chửi nhau vì đất đai.',
      dynamicSign: 'Gặp hai người đánh nhau chảy máu bên đường.',
    },
    4: {
      relation: 'Môn Cung Tỷ Hòa',
      status: 'Hung',
      description: 'Thương Mộc hòa Tốn Mộc. Mưu việc bị người khác tranh cướp công trạng, đau nhức gân cốt.',
      staticSign: 'Bị trộm vặt hoa quả hoặc đồ dùng trong sân vườn.',
      dynamicSign: 'Gặp người vác cành cây khô gãy hoặc tiếng quạ kêu trên ngọn cây.',
    },
    6: {
      relation: 'Cung Khắc Môn (Môn Chế)',
      status: 'Bình',
      description: 'Càn Kim chém Thương Mộc. Hung môn bị chế ngự, kẻ xấu bị pháp luật trừng phạt thích đáng.',
      staticSign: 'Kẻ vu cáo bị cơ quan công an xử lý nghiêm.',
      dynamicSign: 'Gặp cảnh sát giao thông dừng xe xử phạt người vi phạm.',
    },
    7: {
      relation: 'Cung Khắc Môn (Môn Chế)',
      status: 'Bình',
      description: 'Đoài Kim phạt Thương Mộc. Đòi lại được một phần tài sản sau khi tranh cãi kịch liệt.',
      staticSign: 'Vợ chồng cãi cọ nhưng sau đó làm hòa.',
      dynamicSign: 'Gặp người cầm dao mổ gà vịt kêu quang quác.',
    },
    8: {
      relation: 'Môn Khắc Cung (Môn Bách)',
      status: 'Đại Hung',
      description: 'Thương Mộc phạt Cấn Thổ. Môn Bách, trẻ con bị thương tích chân tay, chó cắn, gãy xương.',
      staticSign: 'Trẻ con trong nhà bị ngã gãy tay chân hoặc chó mèo cắn.',
      dynamicSign: 'Gặp người chống gậy đi tập tễnh hoặc xe máy đổ kềnh.',
    },
    9: {
      relation: 'Môn Sinh Cung',
      status: 'Hung',
      description: 'Thương Mộc sinh Ly Hỏa. Nóng nảy sinh hỏa hoạn, kiện tụng gay gắt không hồi kết.',
      staticSign: 'Tranh cãi nảy lửa trong cuộc họp cơ quan.',
      dynamicSign: 'Gặp đám cháy bốc khói đen hoặc người vác đuốc la hét.',
    },
  },

  'Đỗ Môn': {
    1: {
      relation: 'Cung Sinh Môn',
      status: 'Cát',
      description: 'Khảm Thủy sinh Đỗ Mộc. Lợi cho việc trốn tránh, ẩn nấp, nghiên cứu mật mã, tu tập bế quan.',
      staticSign: 'Ngồi trong phòng kín đọc sách nghiên cứu đạt nhiều thành tựu lớn.',
      dynamicSign: 'Gặp người câu cá tĩnh lặng hoặc người mặc áo đạo sĩ đi qua.',
    },
    2: {
      relation: 'Môn Khắc Cung (Môn Bách)',
      status: 'Hung',
      description: 'Đỗ Mộc bế tắc Khôn Thổ. Bế môn tỏa cảng, tiền bạc tắc nghẽn, kinh doanh ế ẩm.',
      staticSign: 'Cửa hàng cả ngày không có một bóng khách.',
      dynamicSign: 'Gặp đường cụt bị rào chắn hoặc biển báo cấm đi lại.',
    },
    3: {
      relation: 'Môn Cung Tỷ Hòa',
      status: 'Bình',
      description: 'Đỗ Mộc hòa Chấn Mộc. Giữ bí mật an toàn, tránh được tai mắt của kẻ thù.',
      staticSign: 'Tài liệu mật được cất giữ an toàn tuyệt đối.',
      dynamicSign: 'Gặp người đeo khẩu trang kín mít vội vã đi qua.',
    },
    4: {
      relation: 'Môn Cung Tỷ Hòa (Phục Ngâm)',
      status: 'Bình',
      description: 'Đỗ Mộc về Tốn 4 bản cung. Ẩn mình chờ thời cơ, không nên hành động lúc này.',
      staticSign: 'Cơ quan đóng cửa nghỉ phép định kỳ.',
      dynamicSign: 'Gặp sương mù dày đặc che khuất tầm nhìn.',
    },
    6: {
      relation: 'Cung Khắc Môn (Môn Chế)',
      status: 'Cát',
      description: 'Càn Kim phá tan sự bế tắc của Đỗ Mộc. Bí mật bị phơi bày nhưng mang lại sự quang minh.',
      staticSign: 'Vụ án bí mật được cơ quan chức năng làm sáng tỏ.',
      dynamicSign: 'Gặp người cầm chìa khóa mở cánh cổng sắt lớn.',
    },
    7: {
      relation: 'Cung Khắc Môn (Môn Chế)',
      status: 'Cát',
      description: 'Đoài Kim mở khóa Đỗ Mộc. Giải tỏa bế tắc trong giao tiếp, nối lại đàm phán.',
      staticSign: 'Người giận dỗi chịu mở lời nói chuyện làm lành.',
      dynamicSign: 'Gặp người thợ sửa khóa đang mở ổ khóa hỏng.',
    },
    8: {
      relation: 'Môn Khắc Cung (Môn Bách)',
      status: 'Hung',
      description: 'Đỗ Mộc bế Cấn Thổ. Tắc đường, nghẽn mạng viễn thông, hàng hóa kẹt ở cửa khẩu.',
      staticSign: 'Hàng hóa đặt mua bị giữ lại ở hải quan không thông quan được.',
      dynamicSign: 'Gặp đoạn đường sạt lở đá phong tỏa giao thông.',
    },
    9: {
      relation: 'Môn Sinh Cung',
      status: 'Cát',
      description: 'Đỗ Mộc sinh Ly Hỏa. Nung nấu ý chí trong âm thầm, chờ ngày bùng sáng rực rỡ.',
      staticSign: 'Kế hoạch kinh doanh ấp ủ bấy lâu chuẩn bị ra mắt thị trường.',
      dynamicSign: 'Gặp người thắp đèn lồng trong đêm tối.',
    },
  },

  'Cảnh Môn': {
    1: {
      relation: 'Cung Khắc Môn (Môn Chế)',
      status: 'Hung',
      description: 'Khảm Thủy dập tắt Cảnh Hỏa. Hợp đồng bị hủy bỏ, tiếng tăm bị dìm xuống bùn, thị phi.',
      staticSign: 'Nhận được thư từ chối hợp tác hoặc khiếu nại chất lượng dịch vụ.',
      dynamicSign: 'Gặp người đánh rơi cốc chén nước vỡ tan tành.',
    },
    2: {
      relation: 'Môn Sinh Cung',
      status: 'Cát',
      description: 'Cảnh Hỏa sinh Khôn Thổ. Lợi cho việc quảng cáo, tiệc tùng, xuất bản sách báo, ký kết.',
      staticSign: 'Có tiệc mừng liên hoan lớn trong cơ quan hoặc gia đình.',
      dynamicSign: 'Gặp người phát tờ rơi quảng cáo rực rỡ sắc màu.',
    },
    3: {
      relation: 'Cung Sinh Môn',
      status: 'Đại Cát',
      description: 'Chấn Mộc sinh Cảnh Hỏa. Tiếng tăm vang dội như sấm truyền, văn chương phát tiết đại cát.',
      staticSign: 'Bài viết hoặc video được lan truyền chóng mặt trên mạng.',
      dynamicSign: 'Gặp đoàn biểu diễn múa lân rước đuốc tưng bừng.',
    },
    4: {
      relation: 'Cung Sinh Môn',
      status: 'Đại Cát',
      description: 'Tốn Mộc sinh Cảnh Hỏa. Thư tín bay xa, ký hợp đồng triển lãm nghệ thuật, du lịch danh thắng.',
      staticSign: 'Nhận được giấy mời tham dự dạ tiệc hoàng gia hoặc sự kiện lớn.',
      dynamicSign: 'Gặp đàn chim ngũ sắc bay lượn trên bầu trời quang đãng.',
    },
    6: {
      relation: 'Môn Khắc Cung (Môn Bách)',
      status: 'Hung',
      description: 'Cảnh Hỏa nung Càn Kim. Môn Bách, kiện tụng vì văn thư, cãi nhau với lãnh đạo cấp cao.',
      staticSign: 'Hợp đồng có điều khoản gài bẫy khiến hai bên tranh chấp nảy lửa.',
      dynamicSign: 'Gặp người cãi vã với cảnh sát giao thông bên lề đường.',
    },
    7: {
      relation: 'Môn Khắc Cung (Môn Bách)',
      status: 'Hung',
      description: 'Cảnh Hỏa phạt Đoài Kim. Môn Bách, khẩu thiệt thị phi do khoe khoang hào nhoáng.',
      staticSign: 'Bị bạn bè ghen ghét xoi mói vì ăn mặc quá nổi bật.',
      dynamicSign: 'Gặp người làm rơi vỡ đồ trang sức kim hoàn quý giá.',
    },
    8: {
      relation: 'Môn Sinh Cung',
      status: 'Cát',
      description: 'Cảnh Hỏa sinh Cấn Thổ. Xây dựng danh lam thắng cảnh, nhà hàng khách sạn đắt khách.',
      staticSign: 'Nhà hàng buôn bán phát đạt, khách đặt bàn chật kín.',
      dynamicSign: 'Gặp người gánh hoa quả đỏ rực lên chùa dâng lễ.',
    },
    9: {
      relation: 'Môn Cung Tỷ Hòa (Phục Ngâm)',
      status: 'Bình',
      description: 'Cảnh Hỏa về Ly 9 bản cung. Hào nhoáng bề ngoài nhưng bên trong rỗng tuếch, đề phòng hỏa hoạn.',
      staticSign: 'Đồ điện tử trong nhà bị chập cháy nổ nhẹ.',
      dynamicSign: 'Gặp người mặc áo đỏ rực đang chụp ảnh check-in.',
    },
  },

  'Tử Môn': {
    1: {
      relation: 'Môn Khắc Cung (Môn Bách)',
      status: 'Đại Hung',
      description: 'Tử Thổ chôn vùi Khảm Thủy. Đệ nhất Hung môn bức cung, tang tóc đổ máu, đại họa lâm đầu.',
      staticSign: 'Nghe tin tang lễ hoặc có người thân rơi vào tình trạng nguy kịch.',
      dynamicSign: 'Gặp xe tang chở quan tài hoặc người mặc áo xô gai khóc lóc.',
    },
    2: {
      relation: 'Môn Cung Tỷ Hòa (Phục Ngâm)',
      status: 'Hung',
      description: 'Tử Thổ về Khôn 2 bản cung. Chỉ lợi cho việc chôn cất mồ mả, săn bắn bắt thú, bách sự giai kỵ.',
      staticSign: 'Gia đình đi tảo mộ hoặc bàn bạc chuyện di dời mồ mả tổ tiên.',
      dynamicSign: 'Gặp bãi tha ma hoặc đàn kền kền bay lượn trên trời.',
    },
    3: {
      relation: 'Cung Khắc Môn (Môn Chế)',
      status: 'Bình',
      description: 'Chấn Mộc đâm thủng Tử Thổ. Hung môn bị chế ngự, chết đi sống lại, tai qua nạn khỏi.',
      staticSign: 'Bệnh nhân nguy kịch được bác sĩ cấp cứu hồi sinh kỳ diệu.',
      dynamicSign: 'Gặp chồi non mọc lên từ thân cây gỗ mục bên đường.',
    },
    4: {
      relation: 'Cung Khắc Môn (Môn Chế)',
      status: 'Bình',
      description: 'Tốn Mộc hóa giải Tử Thổ. Thoát khỏi cạm bẫy trong gang tấc nhờ sự nhanh trí.',
      staticSign: 'Hủy bỏ kịp thời hợp đồng lừa đảo của đối tác xấu.',
      dynamicSign: 'Gặp gió thổi bay đám khói đen u ám trên bầu trời.',
    },
    6: {
      relation: 'Môn Sinh Cung',
      status: 'Hung',
      description: 'Tử Thổ sinh Càn Kim. Hung môn sinh Cung, hao tiền tốn của lo việc ma chay hiếu hỉ.',
      staticSign: 'Chi tiêu khoản tiền lớn vào việc ma chay hoặc đền bù thiệt hại.',
      dynamicSign: 'Gặp người mang lễ vật viếng đám tang đi qua.',
    },
    7: {
      relation: 'Môn Sinh Cung',
      status: 'Hung',
      description: 'Tử Thổ sinh Đoài Kim. Khóc lóc tang tóc, mất mát người thân hoặc tài sản quý giá.',
      staticSign: 'Trong nhà có tiếng khóc than vì tổn thất tài sản lớn.',
      dynamicSign: 'Gặp đàn bà mặc áo tang đi gục đầu bên đường.',
    },
    8: {
      relation: 'Môn Cung Tỷ Hòa',
      status: 'Hung',
      description: 'Tử Thổ hòa Cấn Thổ. Bế tắc toàn diện, việc ma chay mồ mả cản trở đường làm ăn.',
      staticSign: 'Mộ phần tổ tiên bị động chạm cần phải tạ mộ sám hối.',
      dynamicSign: 'Gặp đống đất mồ mới đắp hoặc người vác xẻng đào huyệt.',
    },
    9: {
      relation: 'Cung Sinh Môn',
      status: 'Đại Hung',
      description: 'Ly Hỏa tiếp sức cho Tử Thổ. Cung sinh Hung môn, tai họa cháy nhà chết người đổ máu.',
      staticSign: 'Hỏa hoạn thiêu rụi tài sản hoặc tai nạn bỏng nặng thương vong.',
      dynamicSign: 'Gặp đám cháy dữ dội hoặc tiếng xe cứu hỏa gầm rú.',
    },
  },

  'Kinh Môn': {
    1: {
      relation: 'Môn Sinh Cung',
      status: 'Hung',
      description: 'Kinh Kim sinh Khảm Thủy. Lo sợ nghi hoặc sinh bệnh tật, trộm cắp quấy phá ban đêm.',
      staticSign: 'Cả đêm mất ngủ vì lo sợ kẻ trộm cạy cửa hoặc mất tiền.',
      dynamicSign: 'Gặp người hớt hải chạy trốn hoặc tiếng chó sủa ran đêm.',
    },
    2: {
      relation: 'Cung Sinh Môn',
      status: 'Hung',
      description: 'Khôn Thổ sinh Kinh Kim. Lo lắng vì chuyện đất đai mồ mả của cha mẹ tổ tiên.',
      staticSign: 'Gia đình họp bàn cãi vã căng thẳng về chuyện chia đất.',
      dynamicSign: 'Gặp người phụ nữ hoảng sợ ngã xe giữa đường.',
    },
    3: {
      relation: 'Môn Khắc Cung (Môn Bách)',
      status: 'Đại Hung',
      description: 'Kinh Kim chém Chấn Mộc. Môn Bách, kinh hãi tột cùng, tai nạn thương tích đổ máu, kiện tụng.',
      staticSign: 'Nhận được giấy triệu tập khẩn cấp của cơ quan điều tra công an.',
      dynamicSign: 'Gặp cảnh sát bắt cướp hoặc tai nạn giao thông kinh hoàng.',
    },
    4: {
      relation: 'Môn Khắc Cung (Môn Bách)',
      status: 'Đại Hung',
      description: 'Kinh Kim phạt Tốn Mộc. Môn Bách, gia đình tan nát vì tin đồn thất thiệt, sợ hãi phát điên.',
      staticSign: 'Bị đe dọa tống tiền qua mạng khiến tinh thần hoảng loạn.',
      dynamicSign: 'Gặp người vừa chạy vừa la hét thất thanh trên đường.',
    },
    6: {
      relation: 'Môn Cung Tỷ Hòa',
      status: 'Hung',
      description: 'Kinh Kim hòa Càn Kim. Tranh chấp pháp lý với cơ quan cấp trên, hồi hộp chờ tuyên án.',
      staticSign: 'Đang chờ phán quyết cuối cùng của tòa án với tâm trạng lo âu.',
      dynamicSign: 'Gặp người mang gông cùm hoặc đoàn xe cảnh sát dẫn giải tù nhân.',
    },
    7: {
      relation: 'Môn Cung Tỷ Hòa (Phục Ngâm)',
      status: 'Hung',
      description: 'Kinh Kim về Đoài 7 bản cung. Kinh môn phục ngâm, mồm loa mép giải cãi cọ, tiếng sét kinh hồn.',
      staticSign: 'Hai người đàn bà chửi nhau cả ngày không dứt.',
      dynamicSign: 'Nghe tiếng sét đánh chát chúa hoặc chuông báo động réo vang.',
    },
    8: {
      relation: 'Cung Sinh Môn',
      status: 'Hung',
      description: 'Cấn Thổ sinh Kinh Kim. Lo lắng sợ hãi vì trẻ con ốm đau tai nạn.',
      staticSign: 'Con cái bị sốt cao co giật phải đưa đi viện gấp trong đêm.',
      dynamicSign: 'Gặp trẻ em khóc thét tìm mẹ trên phố đông.',
    },
    9: {
      relation: 'Cung Khắc Môn (Môn Chế)',
      status: 'Bình',
      description: 'Ly Hỏa nung Kinh Kim. Lửa sáng xua tan nỗi sợ hãi, tai qua nạn khỏi sau cơn giật mình.',
      staticSign: 'Hiểu lầm được giải tỏa, mọi người ôm nhau mừng rỡ.',
      dynamicSign: 'Gặp người đốt pháo hoa hoặc thắp đuốc xua đuổi thú dữ.',
    },
  },
};

// -------------------------------------------------------------------------------------------------
// 3. CỬU TINH VƯỢNG TƯỚNG HƯU TÙ PHẾ TẠI 9 CUNG & BẢN CHẤT CÁT HUNG
// -------------------------------------------------------------------------------------------------
export const STAR_PROFILES: Record<string, { element: string; nature: string; baseSign: string }> = {
  'Thiên Bồng': {
    element: 'Thủy',
    nature: 'Đại Hung Tinh (Đạo Tặc Chi Tinh)',
    baseSign: 'Chủ mưu lược thâm sâu, đạo tặc trộm cắp, thủy tai, cờ bạc, mưu sự lớn nhưng hiểm trở.',
  },
  'Thiên Nhuế': {
    element: 'Thổ',
    nature: 'Đại Hung Tinh (Bệnh Phù Chi Tinh)',
    baseSign: 'Chủ bệnh tật kinh niên, bác sĩ, bằng hữu, tiểu nhân, cần tìm thầy giỏi cứu chữa.',
  },
  'Thiên Xung': {
    element: 'Mộc',
    nature: 'Thứ Cát Tinh (Bác Kích Dũng Tinh)',
    baseSign: 'Chủ dũng cảm, đánh trận xông pha, thể thao, đốn cây khai hoang, làm việc nhanh như chớp.',
  },
  'Thiên Phụ': {
    element: 'Mộc',
    nature: 'Đại Cát Tinh (Văn Khúc Giáo Dục)',
    baseSign: 'Chủ văn chương khoa cử, giáo dục đào tạo, quý nhân phò trợ, mở trường lập viện đắc ý.',
  },
  'Thiên Cầm': {
    element: 'Thổ',
    nature: 'Chí Tôn Cát Tinh (Trung Cung Thái Thượng)',
    baseSign: 'Trung ương Thổ tôn quý, thống lĩnh muôn sao, bách sự giai cát, vạn họa tiêu tan.',
  },
  'Thiên Tâm': {
    element: 'Kim',
    nature: 'Đại Cát Tinh (Lãnh Đạo Trị Liệu)',
    baseSign: 'Chủ mưu lược cơ quan đầu não, danh y cứu người, lãnh đạo trị quốc, dẹp loạn an dân.',
  },
  'Thiên Trụ': {
    element: 'Kim',
    nature: 'Hung Tinh (Phá Quân Hủy Hoại)',
    baseSign: 'Chủ khẩu tài hùng biện, ẩn dật, phá hoại công trình, sát phạt hiểm độc, đề phòng thị phi.',
  },
  'Thiên Nhậm': {
    element: 'Thổ',
    nature: 'Đại Cát Tinh (Hiền Lương Điền Sản)',
    baseSign: 'Chủ hiền lành đôn hậu, mua bán đất đai bất động sản, xây dựng chùa chiền, sống lâu giàu có.',
  },
  'Thiên Anh': {
    element: 'Hỏa',
    nature: 'Thứ Cát Tinh (Hào Nhoáng Bộc Phát)',
    baseSign: 'Chủ văn minh lễ nghĩa, danh tiếng hào nhoáng, tiệc tùng dạ hội, đề phòng nóng vội hỏa hoạn.',
  },
};

// -------------------------------------------------------------------------------------------------
// 4. BÁT THẦN DỤNG SỰ & KHẨU QUYẾT BINH THƯ
// -------------------------------------------------------------------------------------------------
export const GOD_PROFILES: Record<string, GodDetail> = {
  'Trực Phù': {
    element: 'Thổ (Đầu Lĩnh Vạn Thần)',
    nature: 'Chí Tôn Cát Thần (Thiên Ất Quý Nhân)',
    significance: 'Bách thần đứng đầu, vạn ác tiêu tan, điềm cát vô cùng.',
    military: 'Đại tướng quân ngự đóng, cờ mở trống dong, uy nghiêm lẫm liệt, đánh đâu thắng đó.',
    divination: 'Gặp gỡ lãnh đạo cấp cao nhất, ký hợp đồng quyết định, kiện tụng tất thắng.',
  },
  'Đằng Xà': {
    element: 'Hỏa (Âm Hỏa)',
    nature: 'Hung Thần (Quái Dị Kinh Khủng)',
    significance: 'Chủ hư giả quái dị, ác mộng, kinh hoàng, trói buộc dây dưa.',
    military: 'Trong quân đề phòng hoang mang, tin đồn thất thiệt, quái dị kinh hãi đêm tối.',
    divination: 'Đề phòng kẻ lừa đảo đa cấp, trói buộc nợ nần, mơ thấy ma quỷ ác mộng.',
  },
  'Thái Âm': {
    element: 'Kim (Âm Kim Tinh Tú)',
    nature: 'Cát Thần (Ẩn Nặc Hộ Vệ)',
    significance: 'Chủ ngầm che chở, âm đức, mưu sự kín đáo, hòa giải êm thấm.',
    military: 'Lợi cho xuất quân ban đêm, mai phục thám thính, giấu quân sâu kín trong rừng.',
    divination: 'Mưu việc ngầm, giao dịch bảo mật, gặp quý nhân nữ giới nâng đỡ.',
  },
  'Lục Hợp': {
    element: 'Mộc (Âm Mộc Hợp Khí)',
    nature: 'Cát Thần (Hòa Hợp Kết Hôn)',
    significance: 'Chủ hòa hợp, người làm mối, liên quân, giao thương buôn bán.',
    military: 'Lợi cho kết minh đồng minh, hòa đàm ngưng chiến, tuyển mộ binh sĩ.',
    divination: 'Cưới hỏi đại cát, ký kết hợp tác kinh doanh, nhiều người chung tay giúp sức.',
  },
  'Bạch Hổ': {
    element: 'Kim (Kim Sát Hung Bạo / Câu Trận)',
    nature: 'Cực Hung Thần (Sát Phạt Thương Tích)',
    significance: 'Chủ đổ máu, tai nạn, đao kiếm sát phạt, quan phi tù tội, chết chóc.',
    military: 'Cực kỳ hung hãn, kỵ phát động trực diện, đề phòng tướng lĩnh bị thương vong.',
    divination: 'Đề phòng tai nạn giao thông đổ máu, mổ xẻ phẫu thuật, chó dữ cắn, kiện cáo dữ dội.',
  },
  'Huyền Vũ': {
    element: 'Thủy (Âm Thủy Đạo Tặc / Chu Tước)',
    nature: 'Hung Thần (Đạo Tặc Thất Thoát)',
    significance: 'Chủ trộm cắp, lừa dối, ám toán, mất mát tài sản, dâm ô.',
    military: 'Đề phòng gián điệp nội gián, cướp lương thảo, nước lũ ngập doanh trại.',
    divination: 'Cẩn thận mất ví tiền, bị hack tài khoản ngân hàng, kẻ tiểu nhân đâm sau lưng.',
  },
  'Cửu Địa': {
    element: 'Thổ (Hậu Đức Tải Vật)',
    nature: 'Cát Thần (Kiên Cố Trường Tồn)',
    significance: 'Chủ tĩnh lặng, hạ trại đóng lũy kiên cố, nuôi dưỡng tích lũy lâu dài.',
    military: 'Lợi cho phòng thủ hạ trại, đắp thành đào hào, giấu vũ khí sâu trong lòng đất.',
    divination: 'Mua bất động sản giữ tiền an toàn tuyệt đối, mưu việc lâu dài trường cửu.',
  },
  'Cửu Thiên': {
    element: 'Kim (Càn Dương Cực Thịnh)',
    nature: 'Đại Cát Thần (Phi Thăng Vũ Bão)',
    significance: 'Chủ bay cao vạn dặm, tiến công vũ bão, danh tiếng vang dội tầng trời.',
    military: 'Lợi cho xuất quân đánh phủ đầu, hỏa công pháo binh, đánh nhanh thắng nhanh.',
    divination: 'Đi máy bay xuất ngoại, thăng quan vùn vụt, công bố dự án chấn động thị trường.',
  },
};
